services:
  postgres-db:
    image: postgres:16-alpine
    container_name: sparkcore-postgres
    environment:
      POSTGRES_USER: sparkcore_user
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: sparkcore_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sparkcore_user -d sparkcore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # In-Memory Datenspeicher für Rate Limiting und Caching
  redis-cache:
    image: redis:7-alpine
    container_name: sparkcore-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Apache Kafka (Event Streaming) - KRaft Mode (kein Zookeeper nötig)
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: sparkcore-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  # Web-UI für PostgreSQL (Ersatz für DataGrip)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sparkcore-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sparkcore.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata: