services:
  postgres-db:
    image: postgres:16-alpine
    container_name: sparkcore-postgres
    environment:
      POSTGRES_USER: sparkcore_user
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: sparkcore_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sparkcore_user -d sparkcore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: